// benchmarks/fixtures/webapp_svelte/src/components/LoginForm.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { AuthService } from "../lib/auth";

  let name = "";
  const auth = new AuthService();
  const dispatch = createEventDispatcher<{ loggedIn: string }>();

  function onSubmit() {
    const token = auth.login(name);
    dispatch("loggedIn", token);
  }
</script>

<form on:submit|preventDefault={onSubmit}>
  <input bind:value={name} />
  <button type="submit">Log in</button>
</form>

// benchmarks/fixtures/webapp_vue/src/components/LoginForm.vue
<template>
  <form @submit.prevent="onSubmit">
    <input v-model="name" />
    <button type="submit">Log in</button>
  </form>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { AuthService } from "../lib/auth";

const name = ref("");
const auth = new AuthService();
const emit = defineEmits<{ (e: "loggedIn", token: string): void }>();

function onSubmit() {
  const token = auth.login(name.value);
  emit("loggedIn", token);
}
</script>
