// benchmarks/fixtures/webapp_svelte/src/components/UserBadge.svelte
<script lang="ts">
  import { AuthService } from "../lib/auth";

  export let token: string;
  const auth = new AuthService();

  function describe(value: string): string {
    const claims = auth.currentUser(value);
    return `user:${claims.userId}`;
  }

  $: label = describe(token);
</script>

<span class="badge">{label}</span>

// benchmarks/fixtures/webapp_vue/src/components/UserBadge.vue
<template>
  <span class="badge">{{ label }}</span>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { AuthService } from "../lib/auth";

const props = defineProps<{ token: string }>();
const auth = new AuthService();

const label = computed(() => describe(props.token));

function describe(token: string): string {
  const claims = auth.currentUser(token);
  return `user:${claims.userId}`;
}
</script>
