// benchmarks/fixtures/webapp_vue/src/App.vue
<template>
  <main>
    <LoginForm @loggedIn="onLoggedIn" />
    <UserBadge v-if="token" :token="token" />
  </main>
</template>

<script setup lang="ts">
import { ref } from "vue";
import LoginForm from "./components/LoginForm.vue";
import UserBadge from "./components/UserBadge.vue";

const token = ref("");

function onLoggedIn(value: string) {
  token.value = value;
}
</script>

// benchmarks/fixtures/webapp_react/src/App.tsx
import { useState } from "react";
import { LoginForm } from "./components/LoginForm";
import { UserBadge } from "./components/UserBadge";

export function App() {
  const [token, setToken] = useState("");

  function onLoggedIn(value: string) {
    setToken(value);
  }

  return (
    <main>
      <LoginForm onLoggedIn={onLoggedIn} />
      {token ? <UserBadge token={token} /> : null}
    </main>
  );
}
