// benchmarks/fixtures/webapp_react/src/components/LoginForm.tsx
import { useState } from "react";
import { AuthService } from "../lib/auth";

interface LoginFormProps {
  onLoggedIn: (token: string) => void;
}

export function LoginForm({ onLoggedIn }: LoginFormProps) {
  const [name, setName] = useState("");
  const auth = new AuthService();

  function onSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const token = auth.login(name);
    onLoggedIn(token);
  }

  return (
    <form onSubmit={onSubmit}>
      <input value={name} onChange={(e) => setName(e.target.value)} />
      <button type="submit">Log in</button>
    </form>
  );
}

// benchmarks/fixtures/webapp_svelte/src/components/LoginForm.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { AuthService } from "../lib/auth";

  let name = "";
  const auth = new AuthService();
  const dispatch = createEventDispatcher<{ loggedIn: string }>();

  function onSubmit() {
    const token = auth.login(name);
    dispatch("loggedIn", token);
  }
</script>

<form on:submit|preventDefault={onSubmit}>
  <input bind:value={name} />
  <button type="submit">Log in</button>
</form>
