// benchmarks/fixtures/webapp_react/src/components/UserBadge.tsx
import { AuthService } from "../lib/auth";

interface UserBadgeProps {
  token: string;
}

export function UserBadge({ token }: UserBadgeProps) {
  const auth = new AuthService();

  function describe(value: string): string {
    const claims = auth.currentUser(value);
    return `user:${claims.userId}`;
  }

  return <span className="badge">{describe(token)}</span>;
}

// benchmarks/fixtures/webapp_svelte/src/components/UserBadge.svelte
<script lang="ts">
  import { AuthService } from "../lib/auth";

  export let token: string;
  const auth = new AuthService();

  function describe(value: string): string {
    const claims = auth.currentUser(value);
    return `user:${claims.userId}`;
  }

  $: label = describe(token);
</script>

<span class="badge">{label}</span>
