// benchmarks/fixtures/webapp_vue/src/App.vue
<template>
  <main>
    <LoginForm @loggedIn="onLoggedIn" />
    <UserBadge v-if="token" :token="token" />
  </main>
</template>

<script setup lang="ts">
import { ref } from "vue";
import LoginForm from "./components/LoginForm.vue";
import UserBadge from "./components/UserBadge.vue";

const token = ref("");

function onLoggedIn(value: string) {
  token.value = value;
}
</script>

// benchmarks/fixtures/webapp_svelte/src/App.svelte
<script lang="ts">
  import LoginForm from "./components/LoginForm.svelte";
  import UserBadge from "./components/UserBadge.svelte";

  let token = "";

  function onLoggedIn(event: CustomEvent<string>) {
    token = event.detail;
  }
</script>

<main>
  <LoginForm on:loggedIn={onLoggedIn} />
  {#if token}
    <UserBadge {token} />
  {/if}
</main>
